### ISSUE TITLE
enable styling in survey pages

### ISSUE THREAD

**Issue by giuliomoro** [BrechtDeMan/WebAudioEvaluationTool#44]
Ideally full html/markdown/anything support 
Something as simple as 
````css
#popupTitle {
    white-space: pre-line;
}
````
would already be a big improvement: then you would be able to combine BLOCK_CAPITAL with newlines, resulting in lots of expressive power
